version: '3'

services:
  app:
    build: .
    command: /bin/ash -c "rm -f /usr/src/app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true

volumes:
  bundle:
    driver: local
