name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: build docker-compose
      with:
        bundler_version: ${{ matrix.versions }}
      run: docker-compose build --build-arg BUNDLER_VERSION=${INPUT_BUNDLER_VERSION}
    - name: bundle install
      run: docker-compose run app bundle install
    - name: execute migration
      run: docker-compose run app bundle exec rails db:migrate
    - name: run rspec
      run: docker-compose run app bundle exec rspec
