name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker-compose
      run: docker-compose build
    - name: execute migration
      run: docker-compose run app bundle exec rails db:migrate
    - name: run rspec
      run: docker-compose run app bundle exec rspec
